// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmM5in1tg3naVpt6Kj0D-O-RzjIqNjgUw',
    appId: '1:323744464504:web:9e112dcc0b069ef9f4f78d',
    messagingSenderId: '323744464504',
    projectId: 'shms-7b88d',
    authDomain: 'shms-7b88d.firebaseapp.com',
    storageBucket: 'shms-7b88d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdjA1TbuCzmgp4T3OoqEpalMNOTqYdDcU',
    appId: '1:323744464504:android:faa0d1779a30cfa4f4f78d',
    messagingSenderId: '323744464504',
    projectId: 'shms-7b88d',
    storageBucket: 'shms-7b88d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmM5in1tg3naVpt6Kj0D-O-RzjIqNjgUw',
    appId: '1:323744464504:web:1124a683bc13a2ecf4f78d',
    messagingSenderId: '323744464504',
    projectId: 'shms-7b88d',
    authDomain: 'shms-7b88d.firebaseapp.com',
    storageBucket: 'shms-7b88d.firebasestorage.app',
  );
}
